// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_authentication.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type User } from "../../../user/service/v1/user.pb";

/** 授权类型 */
export enum GrantType {
  /** password - 密码模式（Resource Owner Password Credentials Grant） */
  password = "password",
  /** client_credentials - 客户端模式（Client Credentials Grant） */
  client_credentials = "client_credentials",
  /** refresh_token - 更新令牌 */
  refresh_token = "refresh_token",
}

/** 令牌类型 */
export enum TokenType {
  /** bearer -  */
  bearer = "bearer",
  /** mac -  */
  mac = "mac",
}

/** 用户后台登出 - 请求 */
export interface LogoutRequest {
  id: number;
}

/** 获取当前用户信息 - 请求 */
export interface GetMeRequest {
  id: number;
}

/** 用户后台登录 - 请求 */
export interface LoginRequest {
  /** 用户名，必选项。 */
  username: string;
  /** 用户的密码，必选项。 */
  password: string;
  /** 授权类型，此处的值固定为"password"，必选项。 */
  grant_type: string;
  /** 以空格分隔的范围列表。如果未提供，scope则授权任何范围，默认为空列表。 */
  scope?: string | null | undefined;
  client_id?: string | null | undefined;
  client_secret?: string | null | undefined;
}

/** 用户后台登录 - 回应 */
export interface LoginResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expires_in?:
    | string
    | null
    | undefined;
  /** 以空格分隔的用户授予范围列表。如果未提供，scope则授权任何范围，默认为空列表。 */
  scope?: string | null | undefined;
}

/** 用户刷新令牌 - 请求 */
export interface RefreshTokenRequest {
  /** 更新令牌，用来获取下一次的访问令牌，必选项。 */
  refresh_token: string;
  /** 授权类型，此处的值固定为"refresh_token"，必选项。 */
  grant_type: string;
  /** 以空格分隔的范围列表。如果未提供，scope则授权任何范围，默认为空列表。 */
  scope?: string | null | undefined;
  client_id?: string | null | undefined;
  client_secret?: string | null | undefined;
}

/** 用户刷新令牌 - 回应 */
export interface RefreshTokenResponse {
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refresh_token: string;
  /** 授权类型，此处的值固定为"password"，必选项。 */
  grant_type: string;
}

/** 用户后台登录认证服务 */
export interface AuthenticationService {
  /** 登录 */
  Login(request: LoginRequest): Promise<LoginResponse>;
  /** 登出 */
  Logout(request: LogoutRequest): Promise<Empty>;
  /** 刷新认证令牌 */
  RefreshToken(request: RefreshTokenRequest): Promise<LoginResponse>;
  /** 后台获取已经登录的用户的数据 */
  GetMe(request: GetMeRequest): Promise<User>;
}
