// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_router.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type RouteItem } from "../../../system/service/v1/menu.pb";

/** 查询路由列表 - 回应 */
export interface ListRouteResponse {
  items: RouteItem[];
}

/** 查询权限码列表 - 回应 */
export interface ListPermissionCodeResponse {
  codes: string[];
}

/** 网站后台动态路由服务 */
export interface RouterService {
  /** 查询路由列表 */
  ListRoute(request: Empty): Promise<ListRouteResponse>;
  /** 查询权限码列表 */
  ListPermissionCode(request: Empty): Promise<ListPermissionCodeResponse>;
}
