// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: gnostic/openapi/v3/annotations.proto

/* eslint-disable */

export {};
