// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: system/service/v1/menu.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** 菜单类型 */
export enum MenuType {
  /** FOLDER - 菜单夹 */
  FOLDER = "FOLDER",
  /** MENU - 菜单项 */
  MENU = "MENU",
  /** BUTTON - 按钮 */
  BUTTON = "BUTTON",
}

/** 菜单状态 */
export enum MenuStatus {
  OFF = "OFF",
  ON = "ON",
}

/** 菜单 */
export interface Menu {
  /** 菜单ID */
  id?:
    | number
    | null
    | undefined;
  /** 菜单状态 */
  status?:
    | MenuStatus
    | null
    | undefined;
  /** 菜单类型 */
  type?:
    | MenuType
    | null
    | undefined;
  /** 路由路径 */
  path?:
    | string
    | null
    | undefined;
  /** 重定向地址 */
  redirect?:
    | string
    | null
    | undefined;
  /** 路由别名 */
  alias?:
    | string
    | null
    | undefined;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name?:
    | string
    | null
    | undefined;
  /** 指向的组件 */
  component?:
    | string
    | null
    | undefined;
  /** 路由元信息 */
  meta?:
    | RouteMeta
    | null
    | undefined;
  /** 父节点ID */
  parentId?:
    | number
    | null
    | undefined;
  /** 子节点树 */
  children: Menu[];
  /** 创建时间 */
  createTime?:
    | Timestamp
    | null
    | undefined;
  /** 更新时间 */
  updateTime?:
    | Timestamp
    | null
    | undefined;
  /** 删除时间 */
  deleteTime?: Timestamp | null | undefined;
}

/** 路由项 */
export interface RouteItem {
  /** 子节点树 */
  children: RouteItem[];
  /** 路由路径 */
  path?:
    | string
    | null
    | undefined;
  /** 重定向地址 */
  redirect?:
    | string
    | null
    | undefined;
  /** 路由别名 */
  alias?:
    | string
    | null
    | undefined;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name?:
    | string
    | null
    | undefined;
  /** 指向的组件 */
  component?:
    | string
    | null
    | undefined;
  /** 路由元信息 */
  meta?: RouteMeta | null | undefined;
}

/** 路由元数据 */
export interface RouteMeta {
  /** 激活图标，用于：菜单、tab */
  activeIcon?:
    | string
    | null
    | undefined;
  /** 当前激活的菜单，有时候不想激活现有菜单，需要激活父级菜单时使用 */
  activePath?:
    | string
    | null
    | undefined;
  /** 是否固定标签页 */
  affixTab?:
    | boolean
    | null
    | undefined;
  /** 固定标签页的顺序 */
  affixTabOrder?:
    | number
    | null
    | undefined;
  /** 权限列表，需要特定的角色标识才可以访问 */
  authority: string[];
  /** 徽标 */
  badge?:
    | string
    | null
    | undefined;
  /** 徽标类型 */
  badgeType?:
    | string
    | null
    | undefined;
  /** 徽标颜色 */
  badgeVariants?:
    | string
    | null
    | undefined;
  /** 当前路由的子级在菜单中不展现 */
  hideChildrenInMenu?:
    | boolean
    | null
    | undefined;
  /** 当前路由在面包屑中不展现 */
  hideInBreadcrumb?:
    | boolean
    | null
    | undefined;
  /** 当前路由在菜单中不展现 */
  hideInMenu?:
    | boolean
    | null
    | undefined;
  /** 当前路由在标签页不展现 */
  hideInTab?:
    | boolean
    | null
    | undefined;
  /** 图标，用于：菜单、标签页 */
  icon?:
    | string
    | null
    | undefined;
  /** iframe 地址 */
  iframeSrc?:
    | string
    | null
    | undefined;
  /** 忽略权限，直接可以访问 */
  ignoreAccess?:
    | boolean
    | null
    | undefined;
  /** 开启KeepAlive缓存 */
  keepAlive?:
    | boolean
    | null
    | undefined;
  /** 外链-跳转路径 */
  link?:
    | string
    | null
    | undefined;
  /** 路由是否已经加载过 */
  loaded?:
    | boolean
    | null
    | undefined;
  /** 标签页最大打开数量 */
  maxNumOfOpenTab?:
    | number
    | null
    | undefined;
  /** 菜单可以看到，但是访问会被重定向到403 */
  menuVisibleWithForbidden?:
    | boolean
    | null
    | undefined;
  /** 在新窗口打开 */
  openInNewWindow?:
    | boolean
    | null
    | undefined;
  /** 排序ID，用于路由->菜单排序 */
  order?:
    | number
    | null
    | undefined;
  /** 标题名称，路由上显示的标题 */
  title?: string | null | undefined;
}

/** 查询菜单列表 - 回应 */
export interface ListMenuResponse {
  items: Menu[];
  total: number;
}

/** 查询菜单详情 - 请求 */
export interface GetMenuRequest {
  id: number;
}

/** 创建菜单 - 请求 */
export interface CreateMenuRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  menu: Menu | null;
}

/** 更新菜单 - 请求 */
export interface UpdateMenuRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  menu:
    | Menu
    | null;
  /** 要更新的字段列表 */
  updateMask:
    | string[]
    | null;
  /** 如果设置为true的时候，资源不存在则会新增(插入)，并且在这种情况下`updateMask`字段将会被忽略。 */
  allowMissing?: boolean | null | undefined;
}

/** 删除菜单 - 请求 */
export interface DeleteMenuRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  id: number;
}

/** 后台菜单服务 */
export interface MenuService {
  /** 查询菜单列表 */
  ListMenu(request: PagingRequest): Promise<ListMenuResponse>;
  /** 查询菜单详情 */
  GetMenu(request: GetMenuRequest): Promise<Menu>;
  /** 创建菜单 */
  CreateMenu(request: CreateMenuRequest): Promise<Empty>;
  /** 更新菜单 */
  UpdateMenu(request: UpdateMenuRequest): Promise<Empty>;
  /** 删除菜单 */
  DeleteMenu(request: DeleteMenuRequest): Promise<Empty>;
}
