// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: pagination/v1/pagination.proto

/* eslint-disable */
import { type Any } from "../../google/protobuf/any.pb";

/** 排序类型 */
export enum SortOrder {
  /** UNSORTED - 不排序 */
  UNSORTED = "UNSORTED",
  /** ASCENDING - 升序 */
  ASCENDING = "ASCENDING",
  /** DESCENDING - 降序 */
  DESCENDING = "DESCENDING",
}

/** 分页通用请求 */
export interface PagingRequest {
  /** 当前页码 */
  page?:
    | number
    | null
    | undefined;
  /** 每页的行数 */
  pageSize?:
    | number
    | null
    | undefined;
  /** 与过滤参数 */
  query?:
    | string
    | null
    | undefined;
  /** 或过滤参数 */
  or?:
    | string
    | null
    | undefined;
  /** 排序条件 */
  orderBy: string[];
  /** 是否不分页 */
  nopaging?:
    | boolean
    | null
    | undefined;
  /** 字段掩码 */
  field_mask: string[] | null;
}

/** 分页通用结果 */
export interface PagingResponse {
  /** 总数 */
  total: number;
  /** 分页数据 */
  items: Any[];
}
