// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: user/service/v1/organization.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** 部门 */
export interface Organization {
  id: number;
  name?: string | null | undefined;
  parentId?: number | null | undefined;
  orderNo?: number | null | undefined;
  status?: string | null | undefined;
  remark?: string | null | undefined;
  children: Organization[];
  createTime?: Timestamp | null | undefined;
  updateTime?: Timestamp | null | undefined;
  deleteTime?: Timestamp | null | undefined;
}

/** 部门列表 - 答复 */
export interface ListOrganizationResponse {
  items: Organization[];
  total: number;
}

/** 部门数据 - 请求 */
export interface GetOrganizationRequest {
  id: number;
}

/** 创建部门 - 请求 */
export interface CreateOrganizationRequest {
  operatorId?: number | null | undefined;
  org: Organization | null;
}

/** 更新部门 - 请求 */
export interface UpdateOrganizationRequest {
  operatorId?: number | null | undefined;
  org: Organization | null;
  updateMask: string[] | null;
  allowMissing?: boolean | null | undefined;
}

/** 删除部门 - 请求 */
export interface DeleteOrganizationRequest {
  operatorId?: number | null | undefined;
  id: number;
}

/** 部门管理服务 */
export interface OrganizationService {
  /** 查询部门列表 */
  ListOrganization(request: PagingRequest): Promise<ListOrganizationResponse>;
  /** 查询部门详情 */
  GetOrganization(request: GetOrganizationRequest): Promise<Organization>;
  /** 创建部门 */
  CreateOrganization(request: CreateOrganizationRequest): Promise<Empty>;
  /** 更新部门 */
  UpdateOrganization(request: UpdateOrganizationRequest): Promise<Empty>;
  /** 删除部门 */
  DeleteOrganization(request: DeleteOrganizationRequest): Promise<Empty>;
}
