// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: user/service/v1/position.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** 职位 */
export interface Position {
  id: number;
  name?: string | null | undefined;
  parentId?: number | null | undefined;
  orderNo?: number | null | undefined;
  code?: string | null | undefined;
  status?: string | null | undefined;
  remark?: string | null | undefined;
  createTime?: Timestamp | null | undefined;
  updateTime?: Timestamp | null | undefined;
  deleteTime?: Timestamp | null | undefined;
}

/** 获取职位列表 - 答复 */
export interface ListPositionResponse {
  items: Position[];
  total: number;
}

/** 获取职位数据 - 请求 */
export interface GetPositionRequest {
  id: number;
}

/** 创建职位 - 请求 */
export interface CreatePositionRequest {
  operatorId?: number | null | undefined;
  position: Position | null;
}

/** 更新职位 - 请求 */
export interface UpdatePositionRequest {
  operatorId?: number | null | undefined;
  position: Position | null;
  updateMask: string[] | null;
  allowMissing?: boolean | null | undefined;
}

/** 删除职位 - 请求 */
export interface DeletePositionRequest {
  operatorId?: number | null | undefined;
  id: number;
}

/** 职位服务 */
export interface PositionService {
  /** 查询职位列表 */
  ListPosition(request: PagingRequest): Promise<ListPositionResponse>;
  /** 查询职位详情 */
  GetPosition(request: GetPositionRequest): Promise<Position>;
  /** 创建职位 */
  CreatePosition(request: CreatePositionRequest): Promise<Empty>;
  /** 更新职位 */
  UpdatePosition(request: UpdatePositionRequest): Promise<Empty>;
  /** 删除职位 */
  DeletePosition(request: DeletePositionRequest): Promise<Empty>;
}
