// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: user/service/v1/role.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** 角色 */
export interface Role {
  id: number;
  name?: string | null | undefined;
  parentId?: number | null | undefined;
  orderNo?: number | null | undefined;
  code?: string | null | undefined;
  status?: string | null | undefined;
  remark?: string | null | undefined;
  createTime?: Timestamp | null | undefined;
  updateTime?: Timestamp | null | undefined;
  deleteTime?: Timestamp | null | undefined;
}

/** 角色列表 - 答复 */
export interface ListRoleResponse {
  items: Role[];
  total: number;
}

/** 角色数据 - 请求 */
export interface GetRoleRequest {
  id: number;
}

/** 创建角色 - 请求 */
export interface CreateRoleRequest {
  operatorId?: number | null | undefined;
  role: Role | null;
}

/** 更新角色 - 请求 */
export interface UpdateRoleRequest {
  operatorId?: number | null | undefined;
  role: Role | null;
  updateMask: string[] | null;
  allowMissing?: boolean | null | undefined;
}

/** 删除角色 - 请求 */
export interface DeleteRoleRequest {
  operatorId?: number | null | undefined;
  id: number;
}

/** 角色服务 */
export interface RoleService {
  /** 查询角色列表 */
  ListRole(request: PagingRequest): Promise<ListRoleResponse>;
  /** 查询角色详情 */
  GetRole(request: GetRoleRequest): Promise<Role>;
  /** 创建角色 */
  CreateRole(request: CreateRoleRequest): Promise<Empty>;
  /** 更新角色 */
  UpdateRole(request: UpdateRoleRequest): Promise<Empty>;
  /** 删除角色 */
  DeleteRole(request: DeleteRoleRequest): Promise<Empty>;
}
