// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: user/service/v1/role.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** 角色 */
export interface Role {
  /** 角色ID */
  id?:
    | number
    | null
    | undefined;
  /** 角色名称 */
  name?:
    | string
    | null
    | undefined;
  /** 排序号 */
  orderNo?:
    | number
    | null
    | undefined;
  /** 角色值 */
  code?: string | null | undefined;
  status?:
    | string
    | null
    | undefined;
  /** 备注 */
  remark?:
    | string
    | null
    | undefined;
  /** 父节点ID */
  parentId?:
    | number
    | null
    | undefined;
  /** 子节点树 */
  children: Role[];
  /** 创建时间 */
  createTime?:
    | Timestamp
    | null
    | undefined;
  /** 更新时间 */
  updateTime?:
    | Timestamp
    | null
    | undefined;
  /** 删除时间 */
  deleteTime?: Timestamp | null | undefined;
}

/** 角色列表 - 答复 */
export interface ListRoleResponse {
  items: Role[];
  total: number;
}

/** 角色数据 - 请求 */
export interface GetRoleRequest {
  id: number;
}

/** 创建角色 - 请求 */
export interface CreateRoleRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  role: Role | null;
}

/** 更新角色 - 请求 */
export interface UpdateRoleRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  role:
    | Role
    | null;
  /** 要更新的字段列表 */
  updateMask:
    | string[]
    | null;
  /** 如果设置为true的时候，资源不存在则会新增(插入)，并且在这种情况下`updateMask`字段将会被忽略。 */
  allowMissing?: boolean | null | undefined;
}

/** 删除角色 - 请求 */
export interface DeleteRoleRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  id: number;
}

/** 角色服务 */
export interface RoleService {
  /** 查询角色列表 */
  ListRole(request: PagingRequest): Promise<ListRoleResponse>;
  /** 查询角色详情 */
  GetRole(request: GetRoleRequest): Promise<Role>;
  /** 创建角色 */
  CreateRole(request: CreateRoleRequest): Promise<Empty>;
  /** 更新角色 */
  UpdateRole(request: UpdateRoleRequest): Promise<Empty>;
  /** 删除角色 */
  DeleteRole(request: DeleteRoleRequest): Promise<Empty>;
}
